.circleci/config.yml
CHANGELOG.rst
setup.py

Create PyPi releases on tag push.
This will create a PyPi release every time that we create a release that matches with this regex  ` /v?[0-9]+(\.[0-9]+)*/` i.e. (v0.1.0, v0.2.0, v1.0.0 ...).
This will done if the tests for that release  are passing.
We have applied these changes successfully in eox-core and flow-control-xblock.

Create PyPi releases on tag push.

---

CHANGELOG.rst
README.rst
eox_tagging/models.py
eox_tagging/test/test_models.py
eox_tagging/validators.py

This PR depends on #14 
This PR adds DateTime validators like:
- BETWEEN: validates that the date is between two dates
For example:
In the configuration:
```
{
...
"validate_expiration_date": {"between": ["2020-10-19 10:20:30", "2020-12-04 10:20:30"]},
}
```
Now, we can only create tags where their expiration_date is greater than "2020-10-19 10:20:30" and less than "2020-12-04 10:20:30" (as date objects). The array must be sorted because it behaves like a range. Should we verify this when validating the settings? @andrey-canon 
- EQUALS: now compares two date objects
- IN: validates that the date as string is in the specified array
Also added API tests using different datetime formats

Datetime validations

---

eox_tagging/admin.py

This PR fixes a typing error in read_only fields after changing valid/invalid to active/inactive

Fixed readonly_field name error

---

eox_tagging/api/v1/serializers.py
eox_tagging/test/test_viewset.py

This PR adds a Meta field to the Tag serializer. This field returns technical information about the tag, like the target or owner.

Added Meta field

---

eox_tagging/api/v1/test/test_viewset.py
eox_tagging/api/v1/viewset.py

This PR separates getting the owner of the tags to be returned when listing/retrieving. I think it is more clear this way to determine how to filter the queryset so tags are only available to the corresponding owner.

Refactor get_queryset in Tag viewset

---

eox_tagging/api/v1/filters.py
eox_tagging/api/v1/test/test_viewset.py

Before this PR the queryset used in the filters was Tag.objects, the problem was that if in the viewset the queryset was filtered then in the filters that filtered queryset was lost and changed for Tag.objects
For example when using the query params `owner_type` and `username` the following was happening:
- The queryset was first filtered by the method get_queryset in the viewset using the param owner_type, 
- then that queryset was filtered by `filters` using the field username. But because we were using Tags.objects in the filters the first filter was lost.

Changed queryset used in filters 

---

eox_tagging/apps.py

Lets use the more standard namespace here.
@andrey-canon could you please check that this is also fixed at the cookiecutter?

Using - instead of _ for the urls namespace

---

eox_tagging/api/v1/filters.py
eox_tagging/api/v1/test/test_viewset.py
eox_tagging/models.py

This PR deletes redundancy in the filters method, replacing find_by_<name>,  where name was a field_name of a target model, with find_by_target_object

Refactor filters

---

Makefile

Install django version defined in django.txt when using `test_requirements` make target

Fix installation of test requirements

---

eox_tagging/api/v1/filters.py
eox_tagging/api/v1/test/test_viewset.py

This PR changes the access to the dictionary containing the values of the access filter. This way we can search using non-existent access values and the filter won't fail

Added safe method to get dictionary value in access filter

---

CHANGELOG.rst
README.rst
docs/source/configuration.rst
eox_tagging/constants.py
eox_tagging/models.py
eox_tagging/test/test_models.py
eox_tagging/validators.py

Now using the configuration object the user will be able to set tag values. For example, if I want to set a specific access level without specifying it while creating each tag, then I will add to EOX_TAGGING_DEFINITIONS the following:
`{"force_access": "PRIVATE"}`

Added force_<FIELD_NAME> to configurations

---

CHANGELOG.rst
eox_tagging/api/v1/filters.py
eox_tagging/api/v1/test/test_viewset.py

This PR adds tests for datetime filters
According to [this](https://django-filter.readthedocs.io/en/1.1.0/ref/filters.html?highlight=datetimefromtorangefilter#datetimefromtorangefilter ) the examples added are the correct way of using datetime filters
activation_date_0 is equivalent toactivation_date _after
activation_date_1 is equivalent to activation_date_before
Also, changes activated_at to activation_date which is the real name

Added datetime filters tests

---

eox_tagging/models.py
eox_tagging/test/test_models.py

Now using a queryset soft delete can be performed. This is helpful in the changes made in eox-taylor, where the tags must match when the user is login in and then the old tags are deleted

Added soft delete using a tag queryset

---

eox_tagging/api/v1/serializers.py
eox_tagging/edxapp_accessors.py

In the serializer, we received target_object/owner_object and it was case sensitive (my error)

Fixed case sensitive issue in serializer

---

eox_tagging/api/v1/filters.py

This PR fixes the following error in Ironwood:
Part of the traceback
```
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django_filters/fields.py", line 64, in __init__
super(DateTimeRangeField, self).__init__(fields, *args, **kwargs)
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django_filters/fields.py", line 25, in __init__
super(RangeField, self).__init__(fields, *args, **kwargs)
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/forms/fields.py", line 996, in __init__
super(MultiValueField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'field_name'
```
This happens because depending on the django_filters version `field_name` or `name` is used. In PR #47 I changed `name` to …

Fix error 500 when getting tags

---

eox_tagging/api/v1/filters.py
eox_tagging/api/v1/serializers.py
eox_tagging/models.py

There were two filters for enrollments:
- The one called `enrollment`
- The one called `enrollments`
The first one was using a method called `filter_by_target_object` and it was not working.
The second one was using a method called `filter_enrollment` and it was working. But that method was redundant given that we had `filter_by_target_object`.
What I did was:
- Fixing `filter_by_target_object` so it could work with enrollments (as it should be)
- Deleted `filter_enrollment` and `enrollments` filter
- Changed `enrollment` for  `enrollments`, so the filter can be used in the same way as before.

Fix enrollment filter

---

eox_tagging/settings/test.py

This PR fixes [this](https://app.circleci.com/pipelines/github/eduNEXT/edunext-platform/1220/workflows/a5be70d9-adfd-4470-b2e7-8e76c69f0ffc/jobs/8093) error in `lms_unit_test`.
It was happening because when loading plugin settings from settings/test.py the function `plugin_settings` was empty, so this setting `EOX_TAGGING_LOAD_PERMISSIONS` didn't have the correct value used when testing.

JU: Fix not loading correct settings when testing

---

eox_tagging/api/v1/permissions.py
eox_tagging/api/v1/test/test_permissions.py

This update was taken from https://github.com/eduNEXT/eox-core/blob/master/eox_core/api/v1/permissions.py

FIxed API permissions error using DOT

---

eox_tagging/api/v1/filters.py
eox_tagging/api/v1/serializers.py
eox_tagging/api/v1/test/test_filters.py
eox_tagging/api/v1/test/test_viewset.py
eox_tagging/models.py

This PR does the following:
1. Before these changes, courseenrollments were filtered using the course_id passed as a parameter and the user found in request.user. It didn't accept the user from query params. Now, we can filter courseenrollments passing course_id or user or neither. For example:
Option 1 (Returns tags on enrollments filtered by course_id and username): 
`?target_type=courseenrollment&enrollment_course_id=course-v1:edX%2BDemoX%2BDemo_Course&enrollment_username=edx`
Option 2 (Returns tags on enrollments filtered by course_id): 
`?target_type=courseenrollment&enrollment_course_id=course-v1:edX%2BDemoX%2BDemo_Course`
Option 3 (Returns tags on enrollments filtered by username):
`?target_type=courseenrollment&enrollment_username=edx`
Option 4 (Returns all tags on enrollments): ` …

Fix courseenrollment filters and refactor

---

.circleci/config.yml
eox_tagging/admin.py
eox_tagging/api/v1/filters.py
eox_tagging/api/v1/serializers.py
eox_tagging/api/v1/viewset.py
eox_tagging/edxapp_wrappers/backends/bearer_authentication_i_v1_test.py
eox_tagging/edxapp_wrappers/backends/course_overview_i_v1.py
eox_tagging/edxapp_wrappers/backends/enrollment_i_v1.py
eox_tagging/models.py
eox_tagging/settings/common.py
eox_tagging/settings/production.py
eox_tagging/settings/test.py
eox_tagging/validators.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/django.txt
requirements/docs.txt
requirements/pip-tools.txt
requirements/test.txt
requirements/tox.txt
setup.py

This PR adds eox-audit-model as a logging mechanism. In preparation for a future PR that will include swagger documentation using [api-doc-tools](https://github.com/edx/api-doc-tools), the requirements were updated and Ironwood support was dropped.
**Changes**
- Drop python2.7 and django 1.11
- Fix/Disable new linting errors due to pylint upgrade
- Updated requirements
- Add eox-audit-model
This [ eox-core PR ](https://github.com/eduNEXT/eox-core/pull/126)offers more context.

Add eox-audit-model and drop support for Ironwood

---

CHANGELOG.rst
eox_tagging/api/v1/filters.py
eox_tagging/api/v1/viewset.py
eox_tagging/api_schema.py
eox_tagging/urls.py

Similarly to [eox-core](https://github.com/eduNEXT/eox-core/pull/125), this PR aims to provide documentation that's more easily accessible.
Changes include:
- A new endpoint `/eox-tagging/api-docs/` that will serve the live documentation
- A backport of this [fix](https://github.com/carltongibson/django-filter/pull/1323)
- Added descriptions for parameters and methods used by the API

Add swagger support and improve REST API documentation

---

.circleci/config.yml
Makefile
requirements/django.txt
requirements/django22.txt
requirements/test.txt
setup.py
tox.ini

This PR adds python 3.8 support to the circleci configuration
Jira issue: https://edunext.atlassian.net/browse/PS2021-428?atlOrigin=eyJpIjoiNTFlYWEyM2MyOGNlNDQyN2FkZjljNzE1MzhjMDRjZjYiLCJwIjoiaiJ9

ci: add py3.8 test support in circleci configuration

---

eox_tagging/api/v1/routers.py
eox_tagging/edxapp_wrappers/backends/enrollment_l_v1.py
eox_tagging/validators.py

Make eox-tagging python 3.8 compatible (and lilac) this includes:
1. Add compatible backend
2. Remove encode imports and encode string calls
3. DRF version used in lilac changes base_name to basename (basename in DRF 3.12 is completely deprecated)

refactor: make py3.8 compatible

---

eox_tagging/api/v1/viewset.py

This PR removes headers when serializing destroy operation

fix: send just serializable objects when auditing

---

eox_tagging/api/v1/viewset.py

This PR allows us to filter using owner_type in swagger api-docs

docs: add owner_type queryparam to swagger docs

---

README.rst
docs/how_to/api.rst

This PR updates the API URL in the current docs. 
Please provide detailed step-by-step instructions for testing this change.
The mismatch was reported in [this](https://github.com/eduNEXT/eox-tagging/issues/84) issue.

fix: update API url in documentation

---

eox_tagging/edxapp_accessors.py

This PR resolves the tagging issue reported for sites here https://github.com/eduNEXT/eox-tagging/issues/90
I test it and the error displayed in the eox-audit-model is:
`
Traceback (most recent call last):
File "/openedx/venv/lib/python3.8/site-packages/eox_tagging/api/v1/serializers.py", line 63, in create
target_object = get_object_from_edxapp(target_type, **data)
File "/openedx/venv/lib/python3.8/site-packages/eox_tagging/edxapp_accessors.py", line 86, in get_object_from_edxapp
return related_object(**kwargs)
TypeError: get_site() got an unexpected keyword argument 'target_id'
`
1. Install the plugin in you instance (you can use [tutor-contrib-edunext-distro](https://github.com/eduNEXT/tutor-contrib-edunext-distro) mango).
2. In the `plugin.py` use ` "version": "dcoa/fix-site-tag"`.
3. …

fix: get_site arg

---

eox_tagging/test/tutor/integration_test_tutor.py

This PR adds validation for the /eox-tagging/eox-info endpoint in the integration test
Checks:
- Integration / integration-test (<17.0.0) (pull_request)
- Integration / integration-test (<18.0.0) (pull_request)
SITE_ID = 2 is used to fix the error: django.contrib.sites.models.Site.DoesNotExist: Site match query does not exist.
When running an instance, SITE_ID is 2, so the setting was overridden so that during testing it also takes the SITE_ID = 2
https://edunext.atlassian.net/browse/DS-993

feat: add api integration test

---

README.rst
docs/how_to/api.rst
docs/how_to/configuration.rst
docs/how_to/model.rst
eox_tagging/settings/common.py
eox_tagging/settings/production.py
eox_tagging/settings/test.py

This PR improves the repository documentation for a better understanding of the eox-tagging plugin.
For repo description:
> eox-tagging is an Open edX plugin that enables tagging of platform objects for categorization, adding information, and more.
Additional information
[JIRA](https://edunext.atlassian.net/browse/DS-971)

docs: improve documentation to explain the actual plugin behavior

---

.github/dependabot.yml
.github/workflows/labeler.yml
.github/workflows/python-publish.yml

This PR adds the `dependabot.yml` file to perform automated upgrading to GitHub Actions. The current configuration creates a Weekly PR (on Mondays) with the changes.
Also, the versions of the workflow actions are updated to use the MAJOR version (if possible).
[AP-1514](https://edunext.atlassian.net/browse/AP-1514)
[AP-1514]: https://edunext.atlassian.net/browse/AP-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: add dependabot config for enable github action auto update `AP-1514`

---

.github/workflows/commitlint.yml

This PR updates the `commitlint.yml` workflow to use Open edX's reusable workflow. This change is mainly to align with the platform workflows.
See the **Lint Commit Messages** job
- https://github.com/eduNEXT/eox-theming/pull/72#issuecomment-2456698858
[AP-1595](https://edunext.atlassian.net/browse/AP-1595)
[AP-1595]: https://edunext.atlassian.net/browse/AP-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: use openedx commitlint workflow `AP-1595`

---

.github/workflows/integration-test.yml
CHANGELOG.md
eox_tagging/__init__.py
setup.cfg

This PR updates the Tutor versions used in integration tests to include Tutor Teak and remove Redwood support.

feat: add teak and remove redwood tutor versions from integration tests
