eduNEXT/eox-tagging

- .circleci/config.yml
This PR adds restore-cache and save-cache to circleci config
> Added cache to circleci config

- .circleci/config.yml
Use CircleCI V2.1 matrix to run the tests
> Use circleci V2.1 matrix

- CHANGELOG.rst
Create changelog with the comment for the first release.
> Add changelog.

- .circleci/config.yml
- CHANGELOG.rst
- eox_tagging/__init__.py
- setup.cfg
> release 0.2.0

- eox_tagging/api/v1/serializers.py
- eox_tagging/test/test_viewset.py
Changed owner_type from required to not required in POST petitions. The Tag owner by default is site.
> Deleted owner in request body

- CHANGELOG.rst
- eox_tagging/__init__.py
- setup.cfg
Add section in the changelog with the information of the new release and run `bumpversion minor`.
> Prepare release v0.3.0

- eox_tagging/api/v1/serializers.py
This PR changes the returning ID in meta field so it returns username for user, course_id for courses and so on
> Changed returning id

- eox_tagging/api/v1/test/test_viewset.py
This PR depends on #29 
This PR adds tests for getting important technical information from meta field
> Test meta field

- CHANGELOG.rst
- eox_tagging/api/v1/test/test_viewset.py
- eox_tagging/api/v1/viewset.py
This PR depends on #17 
This PR includes all tags instead of just valid ones when retrieving them.
> Changed queryset when retrieving objects

- CHANGELOG.rst
- eox_tagging/test/test_views.py
- eox_tagging/urls.py
- eox_tagging/views.py
Added info-view to eox-tagging
> Added eox-info view and tests to eox-tagging

- eox_tagging/admin.py
This PR adds the tag public identifier to the list of displayed values
> Added tag key to admin

- eox_tagging/apps.py
- eox_tagging/settings/aws.py
Deleted the aws settings file and its implications.
**Note:** This PR depends on the changes of #47  in the _filters.py_ file
> Add support to juniper

- eox_tagging/settings/common.py
eox-audit-model was not properly added to the Installed-apps
> Properly add eox-audit-model

- eox_tagging/test/integration/README.rst
- eox_tagging/test/integration/test_api_integration.py
- eox_tagging/test/integration/test_data.json
- tox.ini
Include a simple suit test to check the behavior of the rest API on a live server. The tests are meant to be run explicitly on a Jenkins job.
> Add integration tests and test instructions.

- eox_tagging/api/v1/viewset.py
Remove header since that is  a dict with elements that are not serializable
> fix: Remove headers

- eox_tagging/edxapp_wrappers/backends/enrollment_l_v1.py
> fix: fix wrong get_enrollment_backend import

- eox_tagging/models.py
This PR fixes the following:
When getting tags related to a course, this comparison failed:
` target_type = PROXY_MODEL_NAME if target_type in OPAQUE_KEY_PROXY_MODEL_TARGETS else target_type` because target_type was `courseoverview` and `OPAQUE_KEY_PROXY_MODEL_TARGETS = ["CourseOverview"]`. That comparison was triggered by the filter `filter_by_target_object`. To fix it, I added .lower() to the string comparison.
I also opened this PR adding tests to the Tag manager:  #69 trying to minimize errors in future modifications.
> fix: add case insensitive to string comparison in tag manager

- eox_tagging/test/test_models.py
This PR adds testing to the tag manager with mock objects like CourseEnrollments and CourseOverview.
> test: add testing for queryset Tag Manager

- CHANGELOG.rst
- eox_tagging/settings/common.py
This PR changes default backends from juniper to lilac.
> feat!: add lilac backends as default

- CHANGELOG.rst
- README.rst
Added eox-tagging installation steps with Tutor in the README file.
Just read the README file.
No
> feat: added installation docs with tutor
